### ISSUE TITLE
Tekst

### ISSUE THREAD

**Issue by Dre90** [Dre90/wyciwyg-tdc#11]

**Comment by haggster** [comment]
Intro:
WYCIWYG er inspirert av Code in the Dark og er en konkurranse der du skal skrive HTML og CSS for å kopiere et referansebilde uten mulighet til å forhåndsvise resultatet. Fyll ut feltene under for å starte.
PS! Du har kun 4 minutter på deg (passende emoji?:))

**Comment by haggster** [comment]
Checkbox:
Jeg samtykker til at personopplysninger lagres fram til konkurransen er avsluttet. Opplysningene blir kun brukt til å kontakte deg som eventuell vinner av konkurransen.
<a href="#">Personvernerklæring</a>

**Comment by haggster** [comment]
Personvernerklæring:
Det er frivillig å oppgi personopplysninger på dette nettstedet, men det er en forutsetning for å kunne delta i trekning om premie. Behandlingsgrunnlaget er samtykke fra den enkelte. Bouvet Norge AS er databehandler. Data lagres i AWS (EU) gjennom tjenesten [Supabase](http://supabase.com/).

Alle personopplysninger som samles inn (navn, telefon og e-post) blir kun brukt til å kontakte vinner av konkurransen og slettes når konkurransen er avsluttet, senest innen 31.10.24.
